### ISSUE TITLE
PostgreSQL error

### ISSUE THREAD

**Issue by jrodan** [emdev-limited/activiti-liferay#2]
Using PostgreSQL as database, the following error occurs when a user opens his "My Workflow Taks" Portlet:

Edit: Removed StackTrace. See pasteBin StrackTrace at the bottom

**Comment by akakunin** [comment]
Jan, thank you for notification! We will check this bug

**Comment by jrodan** [comment]
Thank you!
Please keep me on track.

**Comment by jrodan** [comment]
Are there any updates?

**Comment by akakunin** [comment]
Hi! We tested latest version of activiti-web and it works fine with PostgreSQL. From query it looks like you are using some previous version. Could you test with latest version we currently publishing into marketplace: https://drive.google.com/open?id=0B1Y0QwgxNG1SbUpPdGhmdDhyOUU

**Comment by jrodan** [comment]
Hi, 

we have tested it now as you said but the problem still exists!

Caused by: org.postgresql.util.PSQLException: ERROR: operator does not exist: character varying = bigint_  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts._  Position: 230 [Sanitized]

We are using postgres version 9.4.4 .

**Comment by akakunin** [comment]
Hi! Can you send us full stack trace? Problem is - in our case everything works quite fine with PostgreSQL

**Comment by jrodan** [comment]
Hi, 

we reproduced it on a local dev environment:
- Liferay EE 6.2 SP12
- postgreSql-9.4.4
- activiti-web-6.2.17.3

The following error message appears when I start the server (At the end of start process):

http://pastebin.com/XPZquuTY

Any ideas?

Thanks and regards

Jan

**Comment by akakunin** [comment]
Jan, hi! Thank you for stack trace - we will work on the issue

**Comment by akakunin** [comment]
Jan, hi! We was able (finally) reproduce problem. Working on fixing - I will inform as soon as new version will be ready

**Comment by akakunin** [comment]
Hi Jan! New version available for download: https://drive.google.com/open?id=0B1Y0QwgxNG1SQW1LalByZHlOUFU

Could you test it?

From our side we are migrating to use Activiti 5.18 - so, in marketplace this fix will be available together with migration to newer Activiti

**Comment by jrodan** [comment]
Hi, looks very good now! But had to create another bug for a follow up error ;)
