### ISSUE TITLE
Missing table when using postgreSQL

### ISSUE THREAD

**Issue by jrodan** [emdev-limited/activiti-liferay#3]
When using the latest version 6.2.17.3 the following error occurs when using postgreSQL:

http://pastebin.com/kBgfGzZZ

**Comment by akakunin** [comment]
Hi! ACT_HI_PROCINST.tenant_id_  field was added in Activiti 5.16 or so. It looks like you has old database and by some reasons (probably previosly errors) it was not correctly upgraded.
Could you try to reproduce it with clear database (for example remove all ACT_xxx tables).

**Comment by jrodan** [comment]
Perfect. It works now!
